# Generated by Django 4.2.20 on 2025-04-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('requested', 'Order Requested'), ('placed', 'Order Placed'), ('in_transit', 'Material in Transit'), ('received', 'Material Received'), ('qc', 'Material QC'), ('qc_failed', 'Material QC Failed'), ('qc_successful', 'Material QC Successful'), ('handover', 'Material Handover'), ('completed', 'Order Completed')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Order Requested'), ('placed', 'Order Placed'), ('in_transit', 'Material in Transit'), ('received', 'Material Received'), ('qc', 'Material QC'), ('qc_failed', 'Material QC Failed'), ('qc_successful', 'Material QC Successful'), ('handover', 'Material Handover'), ('completed', 'Order Completed')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('requested', 'Order Requested'), ('placed', 'Order Placed'), ('in_transit', 'Material in Transit'), ('received', 'Material Received'), ('qc', 'Material QC'), ('qc_failed', 'Material QC Failed'), ('qc_successful', 'Material QC Successful'), ('handover', 'Material Handover'), ('completed', 'Order Completed')], max_length=20, verbose_name='Status'),
        ),
    ]
