# Generated by Django 4.2.20 on 2025-04-16 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_component_status_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'QC Successful'), ('failed', 'QC Failed')], max_length=20, verbose_name='QC Status')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inspection Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='orders.component', verbose_name='Component')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_records', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Quality Control Record',
                'verbose_name_plural': 'Quality Control Records',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
